import { QrTemplate } from "../types";

export const TEMPLATE_PRESETS: QrTemplate[] = [
  {
    id: "no-border",
    name: "No Border",
    description: "Just the QR code with no added border or tag treatment.",
    frameStyle: "sharp",
    accentColor: "#111111",
    borderStyle: "none",
    fields: [],
  },
  {
    id: "simple-border",
    name: "Simple Border",
    description: "A clean square border around the QR for a basic printable tag.",
    frameStyle: "sharp",
    accentColor: "#1a1d24",
    borderStyle: "simple",
    fields: [],
  },
  {
    id: "fancy-border",
    name: "Fancy Border",
    description: "A framed QR with an inset decorative border for a slightly more finished look.",
    frameStyle: "rounded",
    accentColor: "#18212d",
    borderStyle: "fancy",
    fields: [],
  },
  {
    id: "scan-me",
    name: "Scan Me",
    description: "Simple bordered QR with a fixed scan prompt underneath.",
    frameStyle: "sharp",
    accentColor: "#161c25",
    borderStyle: "simple",
    ctaLabel: "SCAN ME",
    ctaConfig: {
      fieldKey: "cta_text",
      sizeKey: "cta_size",
      minSizePx: 14,
      maxSizePx: 42,
      defaultSizePx: 21,
      maxLines: 2,
      maxWidth: 220,
      chipHeight: 48,
      chipBottomInset: 24,
      chipRadius: 17,
      chipPaddingX: 16,
    },
    fields: [
      {
        key: "cta_text",
        label: "Tag text",
        placeholder: "Type text for this template",
        defaultValue: "SCAN ME",
      },
    ],
  },
  {
    id: "open-link",
    name: "Open Link",
    description: "Rounded framed QR with a fixed action label for quick link tags.",
    frameStyle: "rounded",
    accentColor: "#1a2230",
    borderStyle: "fancy",
    ctaLabel: "OPEN LINK",
    ctaConfig: {
      fieldKey: "cta_text",
      sizeKey: "cta_size",
      minSizePx: 14,
      maxSizePx: 42,
      defaultSizePx: 21,
      maxLines: 2,
      maxWidth: 220,
      chipHeight: 48,
      chipBottomInset: 24,
      chipRadius: 17,
      chipPaddingX: 16,
    },
    fields: [
      {
        key: "cta_text",
        label: "Tag text",
        placeholder: "Type text for this template",
        defaultValue: "OPEN LINK",
      },
    ],
  },
];
