import { QrTemplate } from "../types";

const TEMPLATE_ACCENTS = {
  border: "#1f2b3b",
  cta: "#1f3552",
  loop: "#1f3148",
  hybrid: "#22324c",
} as const;

function createLoopConfig(overrides?: Partial<NonNullable<QrTemplate["loopConfig"]>>): NonNullable<QrTemplate["loopConfig"]> {
  return {
    outerRadius: 18,
    innerRadius: 8,
    stemWidth: 48,
    stemHeight: 14,
    lift: 8,
    ...(overrides ?? {}),
  };
}

function createCtaConfig(overrides?: Partial<NonNullable<QrTemplate["ctaConfig"]>>): NonNullable<QrTemplate["ctaConfig"]> {
  return {
    fieldKey: "cta_text",
    sizeKey: "cta_size",
    fontKey: "cta_font",
    chipHeightKey: "cta_chip_height",
    minSizePx: 14,
    maxSizePx: 84,
    defaultSizePx: 21,
    maxLines: 2,
    maxWidth: 240,
    chipHeight: 44,
    chipBottomInset: 18,
    chipRadius: 17,
    chipPaddingX: 16,
    ...(overrides ?? {}),
  };
}

function createCtaField(defaultValue: string) {
  return {
    key: "cta_text",
    label: "Tag text",
    placeholder: "Enter custom tag text",
    defaultValue,
  };
}

export const TEMPLATE_PRESETS: QrTemplate[] = [
  {
    id: "no-border",
    name: "No Border",
    description: "Just the QR code with no added border or tag treatment.",
    premiumOnly: false,
    frameStyle: "sharp",
    accentColor: TEMPLATE_ACCENTS.border,
    borderStyle: "none",
    bottomBorderMode: "none",
    fields: [],
  },
  {
    id: "simple-border",
    name: "Simple Border",
    description: "A clean square border around the QR for a basic printable tag.",
    premiumOnly: false,
    frameStyle: "sharp",
    accentColor: TEMPLATE_ACCENTS.border,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    fields: [],
  },
  {
    id: "simple-border-round",
    name: "Simple Border Round",
    description: "Clean rounded frame for tags that need softer corners.",
    premiumOnly: false,
    frameStyle: "rounded",
    accentColor: TEMPLATE_ACCENTS.border,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    fields: [],
  },
  {
    id: "fancy-border",
    name: "Fancy Border",
    description: "A framed QR with an inset decorative border for a slightly more finished look.",
    premiumOnly: true,
    frameStyle: "rounded",
    accentColor: TEMPLATE_ACCENTS.border,
    borderStyle: "fancy",
    bottomBorderMode: "normal",
    fields: [],
  },
  {
    id: "scan-me",
    name: "Scan Me",
    description: "Simple bordered QR with a fixed scan prompt underneath.",
    premiumOnly: false,
    frameStyle: "sharp",
    accentColor: TEMPLATE_ACCENTS.cta,
    borderStyle: "simple",
    bottomBorderMode: "fusedLabel",
    ctaLabel: "SCAN ME",
    ctaConfig: createCtaConfig(),
    fields: [createCtaField("SCAN ME")],
  },
  {
    id: "open-link",
    name: "Open Link",
    description: "Rounded framed QR with a fixed action label for quick link tags.",
    premiumOnly: true,
    frameStyle: "rounded",
    accentColor: TEMPLATE_ACCENTS.cta,
    borderStyle: "fancy",
    bottomBorderMode: "normal",
    ctaLabel: "OPEN LINK",
    ctaConfig: createCtaConfig(),
    fields: [createCtaField("OPEN LINK")],
  },
  {
    id: "tap-tag",
    name: "Tap Tag",
    description: "Rounded simple frame with a compact tap prompt.",
    premiumOnly: false,
    frameStyle: "rounded",
    accentColor: TEMPLATE_ACCENTS.cta,
    borderStyle: "simple",
    bottomBorderMode: "fusedLabel",
    ctaLabel: "TAP TAG",
    ctaConfig: createCtaConfig({
      maxWidth: 236,
      chipHeight: 40,
      chipBottomInset: 16,
      chipRadius: 16,
    }),
    fields: [createCtaField("TAP TAG")],
  },
  {
    id: "loop-square",
    name: "Loop Square",
    description: "Keyring loop with square corners — no text label.",
    premiumOnly: true,
    frameStyle: "sharp",
    accentColor: TEMPLATE_ACCENTS.loop,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    loopConfig: createLoopConfig(),
    fields: [],
  },
  {
    id: "loop-round",
    name: "Loop Round",
    description: "Keyring loop with rounded corners — no text label.",
    premiumOnly: false,
    frameStyle: "rounded",
    accentColor: TEMPLATE_ACCENTS.loop,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    loopConfig: createLoopConfig(),
    fields: [],
  },
  {
    id: "loop-circle",
    name: "Loop Circle",
    description: "Keyring loop with circular frame treatment and no text label.",
    premiumOnly: true,
    frameStyle: "circle",
    accentColor: TEMPLATE_ACCENTS.loop,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    loopConfig: createLoopConfig({
      outerRadius: 20,
      innerRadius: 9,
      stemWidth: 50,
    }),
    fields: [],
  },
  {
    id: "loop-square-text",
    name: "Loop Square + Text",
    description: "Square-cornered keyring loop with an editable scan label.",
    premiumOnly: true,
    frameStyle: "sharp",
    accentColor: TEMPLATE_ACCENTS.hybrid,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    loopConfig: createLoopConfig(),
    ctaLabel: "SCAN ME",
    ctaConfig: createCtaConfig({
      maxWidth: 238,
      chipHeight: 42,
      chipBottomInset: 16,
      chipRadius: 22,
    }),
    fields: [createCtaField("SCAN ME")],
  },
  {
    id: "loop-round-text",
    name: "Loop Round + Text",
    description: "Rounded-corner keyring loop with an editable scan label.",
    premiumOnly: true,
    frameStyle: "rounded",
    accentColor: TEMPLATE_ACCENTS.hybrid,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    loopConfig: createLoopConfig(),
    ctaLabel: "SCAN ME",
    ctaConfig: createCtaConfig({
      maxWidth: 238,
      chipHeight: 42,
      chipBottomInset: 16,
      chipRadius: 22,
    }),
    fields: [createCtaField("SCAN ME")],
  },
  {
    id: "loop-circle-text",
    name: "Loop Circle + Text",
    description: "Circular keyring loop with an editable action label.",
    premiumOnly: true,
    frameStyle: "circle",
    accentColor: TEMPLATE_ACCENTS.hybrid,
    borderStyle: "simple",
    bottomBorderMode: "normal",
    loopConfig: createLoopConfig({
      outerRadius: 20,
      innerRadius: 9,
      stemWidth: 50,
    }),
    ctaLabel: "OPEN",
    ctaConfig: createCtaConfig({
      maxWidth: 232,
      chipHeight: 40,
      chipBottomInset: 15,
      chipRadius: 20,
      defaultSizePx: 20,
    }),
    fields: [createCtaField("OPEN")],
  },
  {
    id: "loop-round-fancy-text",
    name: "Loop Round Fancy + Text",
    description: "Premium rounded keyring with decorative border and editable text.",
    premiumOnly: true,
    frameStyle: "rounded",
    accentColor: TEMPLATE_ACCENTS.hybrid,
    borderStyle: "fancy",
    bottomBorderMode: "normal",
    loopConfig: createLoopConfig({
      outerRadius: 19,
      innerRadius: 8,
      stemWidth: 50,
    }),
    ctaLabel: "SCAN NOW",
    ctaConfig: createCtaConfig({
      maxWidth: 236,
      chipHeight: 42,
      chipBottomInset: 16,
      chipRadius: 20,
    }),
    fields: [createCtaField("SCAN NOW")],
  },
];

