import { useEffect, useState } from 'react';
import { Redirect, Route } from 'react-router-dom';
import { IonApp, IonRouterOutlet, setupIonicReact } from '@ionic/react';
import { IonReactHashRouter } from '@ionic/react-router';
import { User } from '@supabase/supabase-js';
import EditorPage from './pages/EditorPage';
import AuthPage from './pages/AuthPage';
import AuthCallbackPage from './pages/AuthCallbackPage';
import RedirectPage from './pages/RedirectPage';
import TermsPage from './pages/TermsPage';
import SettingsPage from './pages/SettingsPage';
import AdminPage from './pages/AdminPage';
import { getCurrentUser, getProfile, isOwnerAdminEmail, supabase } from './lib/supabaseClient';
import { backfillShortUrlOrigins } from './lib/storage';
import { isPaidPlan } from './lib/plans';
import { Profile } from './types';

/* Core CSS required for Ionic components to work properly */
import '@ionic/react/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';

/**
 * Ionic Dark Mode
 * -----------------------------------------------------
 * For more info, please see:
 * https://ionicframework.com/docs/theming/dark-mode
 */

/* import '@ionic/react/css/palettes/dark.always.css'; */
/* import '@ionic/react/css/palettes/dark.class.css'; */

/* Theme variables */
import './theme/variables.css';

setupIonicReact();

const ROUTER_BASENAME = import.meta.env.BASE_URL;
const SEO_BASE_URL = 'https://url2stl.com';

type SeoMeta = {
  title: string;
  description: string;
  canonical: string;
};

const DEFAULT_SEO: SeoMeta = {
  title: 'URL 2 STL | Turn Any URL Into a 3D-Printable QR Code',
  description: 'Build 3D-printable QR tags from any URL. Create short links, customize QR templates, and export STL or OBJ files from one editor.',
  canonical: `${SEO_BASE_URL}/`,
};

function getSeoForPath(pathname: string): SeoMeta {
  if (pathname.startsWith('/auth/callback')) {
    return {
      title: 'URL 2 STL | Completing Sign-In',
      description: 'Completing your sign-in so you can generate short links, manage tags, and export 3D files.',
      canonical: `${SEO_BASE_URL}/#/auth/callback`,
    };
  }

  if (pathname.startsWith('/auth')) {
    return {
      title: 'URL 2 STL | Sign In',
      description: 'Sign in with Google to manage premium plans, sync links, and unlock account-backed exports.',
      canonical: `${SEO_BASE_URL}/#/auth`,
    };
  }

  if (pathname.startsWith('/s/')) {
    return {
      title: 'URL 2 STL | Short Link Redirect',
      description: 'Open and track short links generated by URL 2 STL QR tags.',
      canonical: `${SEO_BASE_URL}${window.location.pathname}`,
    };
  }

  if (pathname.startsWith('/terms')) {
    return {
      title: 'URL 2 STL | Terms and Conditions',
      description: 'Read URL 2 STL terms, plan limits, billing policy, and acceptable use guidelines.',
      canonical: `${SEO_BASE_URL}/#/terms`,
    };
  }

  if (pathname.startsWith('/settings')) {
    return {
      title: 'URL 2 STL | Account and Billing Settings',
      description: 'Manage your URL 2 STL plan, logos, billing portal access, and premium usage insights.',
      canonical: `${SEO_BASE_URL}/#/settings`,
    };
  }

  if (pathname.startsWith('/admin')) {
    return {
      title: 'URL 2 STL | Admin Dashboard',
      description: 'Owner controls for account moderation, plans, and usage metrics.',
      canonical: `${SEO_BASE_URL}/#/admin`,
    };
  }

  if (pathname.startsWith('/editor') || pathname === '/') {
    return {
      title: DEFAULT_SEO.title,
      description: DEFAULT_SEO.description,
      canonical: `${SEO_BASE_URL}/#/editor`,
    };
  }

  return DEFAULT_SEO;
}

function setMetaByName(name: string, content: string) {
  const tag = document.querySelector(`meta[name="${name}"]`);
  if (tag) {
    tag.setAttribute('content', content);
  }
}

function setMetaByProperty(property: string, content: string) {
  const tag = document.querySelector(`meta[property="${property}"]`);
  if (tag) {
    tag.setAttribute('content', content);
  }
}

function applySeoMeta(meta: SeoMeta) {
  document.title = meta.title;
  setMetaByName('description', meta.description);
  setMetaByProperty('og:title', meta.title);
  setMetaByProperty('og:description', meta.description);
  setMetaByProperty('og:url', meta.canonical);
  setMetaByName('twitter:title', meta.title);
  setMetaByName('twitter:description', meta.description);

  const canonicalTag = document.querySelector('link[rel="canonical"]');
  if (canonicalTag) {
    canonicalTag.setAttribute('href', meta.canonical);
  }
}

function currentRoutePathname(): string {
  const hash = window.location.hash ?? '';
  const hashPath = hash.startsWith('#') ? hash.slice(1) : hash;
  const [pathname] = hashPath.split('?');
  if (!pathname || pathname === '/') {
    return '/';
  }
  return pathname.startsWith('/') ? pathname : `/${pathname}`;
}

function hasUpgradeSuccessFlag(): boolean {
  const searchParams = new URLSearchParams(window.location.search);
  if (searchParams.get("upgrade") === "success") {
    return true;
  }

  const hash = window.location.hash ?? "";
  const queryIndex = hash.indexOf("?");
  if (queryIndex === -1) {
    return false;
  }

  const hashParams = new URLSearchParams(hash.slice(queryIndex + 1));
  return hashParams.get("upgrade") === "success";
}

function clearUpgradeSuccessFlag() {
  const searchParams = new URLSearchParams(window.location.search);
  if (searchParams.has("upgrade")) {
    searchParams.delete("upgrade");
    const search = searchParams.toString();
    const next = `${window.location.pathname}${search ? `?${search}` : ""}${window.location.hash}`;
    window.history.replaceState({}, "", next);
    return;
  }

  const hash = window.location.hash ?? "";
  const queryIndex = hash.indexOf("?");
  if (queryIndex === -1) {
    return;
  }

  const hashPath = hash.slice(0, queryIndex);
  const hashParams = new URLSearchParams(hash.slice(queryIndex + 1));
  hashParams.delete("upgrade");
  const nextHashQuery = hashParams.toString();
  const nextHash = `${hashPath}${nextHashQuery ? `?${nextHashQuery}` : ""}`;
  const next = `${window.location.pathname}${window.location.search}${nextHash}`;
  window.history.replaceState({}, "", next);
}

const App: React.FC = () => {
  const [user, setUser] = useState<User | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);

  // Fix any localhost short URLs stored in localStorage
  useEffect(() => { backfillShortUrlOrigins(); }, []);

  useEffect(() => {
    const updateSeo = () => {
      applySeoMeta(getSeoForPath(currentRoutePathname()));
    };

    updateSeo();
    window.addEventListener('hashchange', updateSeo);

    return () => {
      window.removeEventListener('hashchange', updateSeo);
    };
  }, []);

  useEffect(() => {
    let mounted = true;

    getCurrentUser().then((current) => {
      if (mounted) {
        setUser(current);
        if (current) {
          getProfile(current.id).then((p) => { if (mounted) setProfile(p); });
        }
      }
    });

    if (!supabase) {
      return () => {
        mounted = false;
      };
    }

    const { data } = supabase.auth.onAuthStateChange((_event, session) => {
      const nextUser = session?.user ?? null;
      setUser(nextUser);
      if (nextUser) {
        getProfile(nextUser.id).then((p) => { if (mounted) setProfile(p); });
      } else {
        setProfile(null);
      }
    });

    return () => {
      mounted = false;
      data.subscription.unsubscribe();
    };
  }, []);

  useEffect(() => {
    if (!user || !hasUpgradeSuccessFlag()) {
      return;
    }

    let cancelled = false;
    let attempts = 0;
    const maxAttempts = 15;
    let intervalId: number | undefined;

    const refreshProfile = async () => {
      attempts += 1;
      const next = await getProfile(user.id);
      if (cancelled) {
        return;
      }

      setProfile(next);

      if (isPaidPlan(next?.plan) || attempts >= maxAttempts) {
        clearUpgradeSuccessFlag();
        if (intervalId !== undefined) {
          window.clearInterval(intervalId);
        }
      }
    };

    void refreshProfile();
    intervalId = window.setInterval(() => {
      void refreshProfile();
    }, 2000);

    return () => {
      cancelled = true;
      if (intervalId !== undefined) {
        window.clearInterval(intervalId);
      }
    };
  }, [user]);

  return (
    <IonApp>
      <IonReactHashRouter basename={ROUTER_BASENAME}>
        <IonRouterOutlet>
          <Route exact path="/editor">
            <EditorPage user={user} profile={profile} />
          </Route>
          <Route exact path="/auth">
            <AuthPage user={user} />
          </Route>
          <Route exact path="/auth/callback">
            <AuthCallbackPage />
          </Route>
          <Route exact path="/s/:code">
            <RedirectPage />
          </Route>
          <Route exact path="/terms">
            <TermsPage />
          </Route>
          <Route exact path="/settings">
            <SettingsPage user={user} profile={profile} />
          </Route>
          <Route exact path="/admin">
            {user && isOwnerAdminEmail(user.email) ? <AdminPage user={user} /> : <Redirect to="/settings" />}
          </Route>
          <Route exact path="/">
            <Redirect to="/editor" />
          </Route>
        </IonRouterOutlet>
      </IonReactHashRouter>
    </IonApp>
  );
};

export default App;
