import { useEffect, useState } from 'react';
import { Redirect, Route } from 'react-router-dom';
import { IonApp, IonRouterOutlet, setupIonicReact } from '@ionic/react';
import { IonReactHashRouter } from '@ionic/react-router';
import { User } from '@supabase/supabase-js';
import EditorPage from './pages/EditorPage';
import AuthPage from './pages/AuthPage';
import AuthCallbackPage from './pages/AuthCallbackPage';
import RedirectPage from './pages/RedirectPage';
import TermsPage from './pages/TermsPage';
import SettingsPage from './pages/SettingsPage';
import AdminPage from './pages/AdminPage';
import FeaturesPage from './pages/FeaturesPage';
import FaqPage from './pages/FaqPage';
import GuidesPage from './pages/GuidesPage';
import { ErrorBoundary } from './components/ErrorBoundary';
import { getCurrentUser, getProfile, isOwnerAdminEmail, supabase } from './lib/supabaseClient';
import { backfillShortUrlOrigins } from './lib/storage';
import { isPaidPlan } from './lib/plans';
import { Profile } from './types';
import { SEO_FAQ_ITEMS } from './constants/seoFaq';

/* Core CSS required for Ionic components to work properly */
import '@ionic/react/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';

/**
 * Ionic Dark Mode
 * -----------------------------------------------------
 * For more info, please see:
 * https://ionicframework.com/docs/theming/dark-mode
 */

/* import '@ionic/react/css/palettes/dark.always.css'; */
/* import '@ionic/react/css/palettes/dark.class.css'; */

/* Theme variables */
import './theme/variables.css';

setupIonicReact();

const ROUTER_BASENAME = import.meta.env.BASE_URL;
const REQUIRE_AUTH = import.meta.env.VITE_REQUIRE_AUTH === 'true';
const SEO_BASE_URL = 'https://url2stl.com';
const SEO_SOCIAL_IMAGE_URL = `${SEO_BASE_URL}/seo-qr.png`;
const SEO_JSONLD_SCRIPT_ID = 'url2stl-seo-jsonld';
const SEO_ORG_ID = `${SEO_BASE_URL}/#organization`;
const SEO_WEBSITE_ID = `${SEO_BASE_URL}/#website`;
const SEO_SOFTWARE_ID = `${SEO_BASE_URL}/#software`;
const SEO_DEFAULT_KEYWORDS = ['free', 'auto', 'stl', 'conversion', 'qr', 'maker', 'obj', '3d model', 'render', 'print'];

type SeoMeta = {
  title: string;
  description: string;
  canonical: string;
};

const DEFAULT_SEO: SeoMeta = {
  title: 'Free 3D QR Code Maker | Auto-Convert URLs to STL/OBJ',
  description: 'Free 3D QR code maker to auto-convert URLs into print-ready STL or OBJ files. Render, customize, and export QR tags for 3D printing in one workspace.',
  canonical: `${SEO_BASE_URL}/`,
};

function getSeoForPath(pathname: string): SeoMeta {
  if (pathname.startsWith('/auth/callback')) {
    return {
      title: 'URL 2 STL | Completing Sign-In',
      description: 'Completing your sign-in so you can generate short links, manage tags, and export 3D files.',
      canonical: `${SEO_BASE_URL}/#/auth/callback`,
    };
  }

  if (pathname.startsWith('/auth')) {
    return {
      title: 'URL 2 STL | Sign In',
      description: 'Sign in with Google to manage premium plans, sync links, and unlock account-backed exports.',
      canonical: `${SEO_BASE_URL}/#/auth`,
    };
  }

  if (pathname.startsWith('/features')) {
    return {
      title: 'Features | Free QR to STL/OBJ Converter and 3D Model Workflow',
      description: 'Compare free and premium features for URL-to-QR conversion, STL/OBJ exports, render controls, and print-ready 3D model settings.',
      canonical: `${SEO_BASE_URL}/#/features`,
    };
  }

  if (pathname.startsWith('/faq')) {
    return {
      title: 'FAQ | Free QR Maker, STL Conversion, OBJ Export, and 3D Printing',
      description: 'Answers to common questions about free QR generation, auto conversion, STL and OBJ exports, rendering, and 3D printing workflows.',
      canonical: `${SEO_BASE_URL}/#/faq`,
    };
  }

  if (pathname.startsWith('/guides')) {
    return {
      title: 'Guides | Auto URL Conversion to QR, STL, OBJ, and 3D Print',
      description: 'Step-by-step guides for makers to convert URLs into QR assets, render 3D previews, and export STL or OBJ files for printing.',
      canonical: `${SEO_BASE_URL}/#/guides`,
    };
  }

  if (pathname.startsWith('/s/')) {
    return {
      title: 'URL 2 STL | Short Link Redirect',
      description: 'Open and track short links generated by URL 2 STL QR tags.',
      canonical: `${SEO_BASE_URL}${window.location.pathname}`,
    };
  }

  if (pathname.startsWith('/terms')) {
    return {
      title: 'URL 2 STL | Terms and Conditions',
      description: 'Read URL 2 STL terms, plan limits, billing policy, and acceptable use guidelines.',
      canonical: `${SEO_BASE_URL}/#/terms`,
    };
  }

  if (pathname.startsWith('/settings')) {
    return {
      title: 'URL 2 STL | Account and Billing Settings',
      description: 'Manage your URL 2 STL plan, logos, billing portal access, and premium usage insights.',
      canonical: `${SEO_BASE_URL}/#/settings`,
    };
  }

  if (pathname.startsWith('/admin')) {
    return {
      title: 'URL 2 STL | Admin Dashboard',
      description: 'Owner controls for account moderation, plans, and usage metrics.',
      canonical: `${SEO_BASE_URL}/#/admin`,
    };
  }

  if (pathname.startsWith('/editor') || pathname === '/') {
    return {
      title: DEFAULT_SEO.title,
      description: DEFAULT_SEO.description,
      canonical: `${SEO_BASE_URL}/#/editor`,
    };
  }

  return DEFAULT_SEO;
}

function setMetaByName(name: string, content: string) {
  const tag = document.querySelector(`meta[name="${name}"]`);
  if (tag) {
    tag.setAttribute('content', content);
  }
}

function setMetaByProperty(property: string, content: string) {
  const tag = document.querySelector(`meta[property="${property}"]`);
  if (tag) {
    tag.setAttribute('content', content);
  }
}

function applySeoMeta(meta: SeoMeta) {
  document.title = meta.title;
  setMetaByName('description', meta.description);
  setMetaByProperty('og:title', meta.title);
  setMetaByProperty('og:description', meta.description);
  setMetaByProperty('og:url', meta.canonical);
  setMetaByName('twitter:title', meta.title);
  setMetaByName('twitter:description', meta.description);
  setMetaByName('twitter:image', SEO_SOCIAL_IMAGE_URL);
  setMetaByName('twitter:card', 'summary_large_image');
  setMetaByProperty('og:image', SEO_SOCIAL_IMAGE_URL);
  setMetaByProperty('og:image:alt', 'URL 2 STL free QR to 3D model maker');

  const canonicalTag = document.querySelector('link[rel="canonical"]');
  if (canonicalTag) {
    canonicalTag.setAttribute('href', meta.canonical);
  }
}

function getKeywordsForPath(pathname: string): string[] {
  if (pathname.startsWith('/features')) {
    return [...SEO_DEFAULT_KEYWORDS, 'url to obj converter', 'print-ready stl'];
  }

  if (pathname.startsWith('/faq')) {
    return [...SEO_DEFAULT_KEYWORDS, 'is it free', 'stl vs obj'];
  }

  if (pathname.startsWith('/guides')) {
    return [...SEO_DEFAULT_KEYWORDS, 'maker guide', 'qr 3d printing'];
  }

  if (pathname.startsWith('/editor') || pathname === '/') {
    return [...SEO_DEFAULT_KEYWORDS, 'url to stl', 'qr code generator'];
  }

  return SEO_DEFAULT_KEYWORDS;
}

function buildStructuredData(pathname: string, meta: SeoMeta) {
  const keywords = getKeywordsForPath(pathname);
  const graph: Array<Record<string, unknown>> = [
    {
      '@id': SEO_ORG_ID,
      '@type': 'Organization',
      name: 'URL 2 STL',
      url: `${SEO_BASE_URL}/`,
      logo: SEO_SOCIAL_IMAGE_URL,
      image: SEO_SOCIAL_IMAGE_URL,
      description: 'Free QR maker and auto URL to STL/OBJ conversion workspace for makers and product teams.',
    },
    {
      '@id': SEO_WEBSITE_ID,
      '@type': 'WebSite',
      name: 'URL 2 STL',
      url: `${SEO_BASE_URL}/`,
      description: DEFAULT_SEO.description,
      inLanguage: 'en',
      publisher: { '@id': SEO_ORG_ID },
      potentialAction: {
        '@type': 'SearchAction',
        target: `${SEO_BASE_URL}/#/guides?query={search_term_string}`,
        'query-input': 'required name=search_term_string',
      },
    },
    {
      '@id': SEO_SOFTWARE_ID,
      '@type': 'SoftwareApplication',
      name: 'URL 2 STL',
      applicationCategory: 'DesignApplication',
      operatingSystem: 'Web',
      inLanguage: 'en',
      image: SEO_SOCIAL_IMAGE_URL,
      isAccessibleForFree: true,
      featureList: [
        'Free QR maker',
        'Auto URL conversion',
        '3D model render preview',
        'STL export',
        'OBJ export',
        'Print-ready output',
      ],
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
        availability: 'https://schema.org/InStock',
      },
      description: DEFAULT_SEO.description,
      url: meta.canonical,
      publisher: { '@id': SEO_ORG_ID },
    },
    {
      '@type': 'WebPage',
      name: meta.title,
      description: meta.description,
      url: meta.canonical,
      inLanguage: 'en',
      keywords,
      isPartOf: { '@id': SEO_WEBSITE_ID },
      about: { '@id': SEO_SOFTWARE_ID },
    },
  ];

  if (pathname.startsWith('/faq')) {
    graph.push({
      '@type': 'FAQPage',
      mainEntity: SEO_FAQ_ITEMS.map((item) => ({
        '@type': 'Question',
        name: item.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: item.answer,
        },
      })),
    });
  }

  return {
    '@context': 'https://schema.org',
    '@graph': graph,
  };
}

function applyStructuredData(pathname: string, meta: SeoMeta) {
  const payload = JSON.stringify(buildStructuredData(pathname, meta));
  let scriptTag = document.getElementById(SEO_JSONLD_SCRIPT_ID) as HTMLScriptElement | null;
  if (!scriptTag) {
    scriptTag = document.createElement('script');
    scriptTag.id = SEO_JSONLD_SCRIPT_ID;
    scriptTag.type = 'application/ld+json';
    document.head.appendChild(scriptTag);
  }
  scriptTag.textContent = payload;
}

function currentRoutePathname(): string {
  const hash = window.location.hash ?? '';
  const hashPath = hash.startsWith('#') ? hash.slice(1) : hash;
  const [pathname] = hashPath.split('?');
  if (!pathname || pathname === '/') {
    return '/';
  }
  return pathname.startsWith('/') ? pathname : `/${pathname}`;
}

function currentRouteWithQuery(): string {
  const hash = window.location.hash ?? '';
  const hashPath = hash.startsWith('#') ? hash.slice(1) : hash;
  if (!hashPath || hashPath === '/') {
    return '/';
  }
  return hashPath.startsWith('/') ? hashPath : `/${hashPath}`;
}

function isAuthPath(pathname: string): boolean {
  return pathname === '/auth' || pathname.startsWith('/auth/callback');
}

function hasUpgradeSuccessFlag(): boolean {
  const searchParams = new URLSearchParams(window.location.search);
  if (searchParams.get("upgrade") === "success") {
    return true;
  }

  const hash = window.location.hash ?? "";
  const queryIndex = hash.indexOf("?");
  if (queryIndex === -1) {
    return false;
  }

  const hashParams = new URLSearchParams(hash.slice(queryIndex + 1));
  return hashParams.get("upgrade") === "success";
}

function clearUpgradeSuccessFlag() {
  const searchParams = new URLSearchParams(window.location.search);
  if (searchParams.has("upgrade")) {
    searchParams.delete("upgrade");
    const search = searchParams.toString();
    const next = `${window.location.pathname}${search ? `?${search}` : ""}${window.location.hash}`;
    window.history.replaceState({}, "", next);
    return;
  }

  const hash = window.location.hash ?? "";
  const queryIndex = hash.indexOf("?");
  if (queryIndex === -1) {
    return;
  }

  const hashPath = hash.slice(0, queryIndex);
  const hashParams = new URLSearchParams(hash.slice(queryIndex + 1));
  hashParams.delete("upgrade");
  const nextHashQuery = hashParams.toString();
  const nextHash = `${hashPath}${nextHashQuery ? `?${nextHashQuery}` : ""}`;
  const next = `${window.location.pathname}${window.location.search}${nextHash}`;
  window.history.replaceState({}, "", next);
}

const App: React.FC = () => {
  const [user, setUser] = useState<User | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [authResolved, setAuthResolved] = useState(false);

  // Fix any localhost short URLs stored in localStorage
  useEffect(() => { backfillShortUrlOrigins(); }, []);

  useEffect(() => {
    const updateSeo = () => {
      const pathname = currentRoutePathname();
      const meta = getSeoForPath(pathname);
      applySeoMeta(meta);
      applyStructuredData(pathname, meta);
    };

    updateSeo();
    window.addEventListener('hashchange', updateSeo);

    return () => {
      window.removeEventListener('hashchange', updateSeo);
    };
  }, []);

  useEffect(() => {
    let mounted = true;

    getCurrentUser().then((current) => {
      if (mounted) {
        setUser(current);
        if (current) {
          getProfile(current.id).then((p) => { if (mounted) setProfile(p); });
        }
        setAuthResolved(true);
      }
    });

    if (!supabase) {
      setAuthResolved(true);
      return () => {
        mounted = false;
      };
    }

    const { data } = supabase.auth.onAuthStateChange((_event, session) => {
      const nextUser = session?.user ?? null;
      setUser(nextUser);
      setAuthResolved(true);
      if (nextUser) {
        getProfile(nextUser.id).then((p) => { if (mounted) setProfile(p); });
      } else {
        setProfile(null);
      }
    });

    return () => {
      mounted = false;
      data.subscription.unsubscribe();
    };
  }, []);

  useEffect(() => {
    if (!REQUIRE_AUTH || !authResolved || user) {
      return;
    }

    const pathname = currentRoutePathname();
    if (isAuthPath(pathname)) {
      return;
    }

    localStorage.setItem('url-qr-stl.return-to', currentRouteWithQuery());
    window.location.hash = '/auth';
  }, [authResolved, user]);

  useEffect(() => {
    if (!user || !hasUpgradeSuccessFlag()) {
      return;
    }

    let cancelled = false;
    let attempts = 0;
    const maxAttempts = 15;

    const refreshProfile = async () => {
      attempts += 1;
      const next = await getProfile(user.id);
      if (cancelled) {
        return;
      }

      setProfile(next);

      if (isPaidPlan(next?.plan) || attempts >= maxAttempts) {
        clearUpgradeSuccessFlag();
        window.clearInterval(intervalId);
      }
    };

    const intervalId = window.setInterval(() => {
      void refreshProfile();
    }, 2000);
    void refreshProfile();

    return () => {
      cancelled = true;
      window.clearInterval(intervalId);
    };
  }, [user]);

  return (
    <ErrorBoundary>
      <IonApp>
        <IonReactHashRouter basename={ROUTER_BASENAME}>
          <IonRouterOutlet>
            <Route exact path="/editor">
              <EditorPage user={user} profile={profile} />
            </Route>
            <Route exact path="/auth">
              <AuthPage user={user} />
            </Route>
            <Route exact path="/auth/callback">
              <AuthCallbackPage />
            </Route>
            <Route exact path="/features">
              <FeaturesPage />
            </Route>
            <Route exact path="/faq">
              <FaqPage />
            </Route>
            <Route exact path="/guides">
              <GuidesPage />
            </Route>
            <Route exact path="/s/:code">
              <RedirectPage />
            </Route>
            <Route exact path="/terms">
              <TermsPage />
            </Route>
            <Route exact path="/settings">
              <SettingsPage user={user} profile={profile} />
            </Route>
            <Route exact path="/admin">
              {user && isOwnerAdminEmail(user.email) ? <AdminPage user={user} /> : <Redirect to="/settings" />}
            </Route>
            <Route exact path="/">
              <Redirect to="/editor" />
            </Route>
          </IonRouterOutlet>
        </IonReactHashRouter>
      </IonApp>
    </ErrorBoundary>
  );
};

export default App;
